name: wells_fargo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  postgres: any
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4

  flutter_gen: any
  flutter_localization: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
